#! /bin/sh

# build: Compile the named variant. Default is SDL2 and SNDFILE
# Usage: s/build [ SDL1 | EMOTION | EMOTION_SDL ] [ AUDIOFILE | SOX ]
#
# s/build EMOTION_SDL SDL1 also works to build the hybrid version using
# SDL1.2 instead of SDL2.0

# Restore the original Makefile.am on exit and force a rebuild on "make"
trap "mv -f Makefile.am.orig Makefile.am; touch Makefile.am" 0 INT

mv -f Makefile.am Makefile.am.orig
cp Makefile.am.orig Makefile.am

for a
do
    echo "$a" | grep -q "[=-]" || echo Checking $a
    case "$a" in
    SDL1)
    	sed -i -e '/^SDL_/s/sdl2-config/sdl-config/' Makefile.am
	;;
    SDL2)
    	# is the default
	continue
	;;
    EMOTION)
	sed -i -e '/^AM_CFLAGS/s/USE_SDL/USE_EMOTION/' \
	       -e '/^AM_CFLAGS/s/SDL_CFLAGS/EMOTION_CFLAGS/' \
	       -e '/^AM_LDFLAGS/s/SDL_LIBS/EMOTION_LIBS/' Makefile.am
	;;
    EMOTION_SDL)	# EFL for graphics, SDL2 for sound
	sed -i -e '/^AM_CFLAGS/s/USE_SDL/USE_EMOTION_SDL/' \
	       -e '/^AM_CFLAGS/s/SDL_CFLAGS/&) $(EMOTION_CFLAGS/' \
	       -e '/^AM_LDFLAGS/s/SDL_LIBS/SDL_LIBS) $(EMOTION_LIBS/' Makefile.am
	;;

    SNDFILE)
	# is the default
	continue
	;;
    AUDIOFILE)
	sed -i -e '/^AM_CFLAGS/s/USE_LIBSNDFILE/USE_LIBAUDIOFILE/' \
	       -e '/^AM_[CLD]*FLAGS/s/SNDFILE_/AUDIOFILE_/' Makefile.am
	;;
    SOX)
	sed -i -e '/^AM_CFLAGS/s/USE_LIBSNDFILE/USE_LIBSOX/' \
	       -e '/^AM_[CLD]*FLAGS/s/SNDFILE_/SOX_/' \
	       Makefile.am
	;;
    *=*|-*)
    	MAKEFLAGS="$MAKEFLAGS $a";
	;;
    *)
    	echo "$a unrecognized"
	echo "Usage: s/build [SDL1|SDL2|EMOTION|EMOTION_SDL] [SOX|AUDIOFILE|SNDFILE]"; exit 1
	;;
    esac
    shift
    # Ensure that the sed scripts modified Makefile.am
    echo "$a" | grep -q '[-=]' || test "$a" = SNDFILE -o "$a" = SDL2 || {
      cmp -s Makefile.am Makefile.am.orig && {
	echo "$0 failed to modify Makefile.am"
	exit 1
      }
    }
done

# "make -s clean" is still noisy
make -s $MAKEFLAGS clean > /dev/null

if make -s -j4 $MAKEFLAGS all
then
    git checkout Makefile.am
else
    status=$?
    echo 'Build fails' 1>&2
    git checkout Makefile.am
    exit $status
fi

exit 0
